---
title: "Precourse preparations"
---


## Required competences

### Knowledge

You should meet the learning outcomes of [First Steps with `R` in Life Sciences](https://www.sib.swiss/training/course/20250203_FSWR).

While this course is designed for beginners in multiomics data integration, knowledge of fundamental biological concepts related to gene expression (RNA-seq), chromatin accessibility (ATAC-seq), histone modifications (ChIP-seq), and DNA methylation is highly recommended. Basic to intermediate `R` programming skills are required as participants will be challenged with more coding and interpretation exercises. We recommend you can confidently handle data manipulation and basic functions in `R`. Please evaluate your `R` skills [here](https://docs.google.com/forms/d/e/1FAIpQLSdIyeuabd_ZOWXgI1MWHapmaOMu20L9ESkLDZiWnpmkpujyOg/viewform?usp=sf_link).

## Technical

Attendees should have a Wi-Fi enabled computer. An **online R and RStudio environment** will be provided. In order to access that environment your computer needs to be able to access http websites (not https). You can check this by browsing to [http://www.httpforever.com](http://www.httpforever.com). However, in case you wish to perform the practical exercises on your own computer, please take a moment to install the following before the course:

- [R](https://cran.r-project.org/) version > 4.2. 
- Latest RStudio version, the [free version](https://rstudio.com/products/rstudio/download/) is perfectly fine.
- The R packages necessary for the course. Find the [`renv`](https://rstudio.github.io/renv/) to install them [here](https://github.com/sib-swiss/multiomics-biological-integration-training/blob/master/renv.lock). 
